[env:blackpill_f411ce]
platform = ststm32
board = blackpill_f411ce
framework = stm32cube
upload_protocol = stlink
extra_scripts =
    pre:platformio_extra.py
build_unflags =
    -mfloat-abi=soft
build_src_filter =
    +<Core>
    +<USB_DEVICE>
    +<Middlewares/Third_Party/FreeRTOS>
    -<EWARM>
    -<Middlewares/Third_Party/FreeRTOS/Source/portable/IAR>
    -<Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_1.c>
    -<Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_2.c>
    -<Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_3.c>
    -<Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_5.c>
build_flags =
    -mfpu=fpv4-sp-d16
    -mfloat-abi=hard
    -I src/Core
    -I src/Core/Inc
    -I src/USB_DEVICE/App
    -I src/USB_DEVICE/Target
    -I src/Middlewares/Third_Party/FreeRTOS/Source/include
    -I src/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2
    -I src/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F
